# Generated by Django 6.1.1 on 2026-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.ImageField(default='', upload_to='statics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaje',
            name='velocidad',
            field=models.IntegerField(default=25),
        ),
    ]
